name: Bump version
on:
  push:
    branches: [ main, master]
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'
      - 'CHANGELOG.md'
      - 'build/**/*'
      - 'dist/**/*'
  workflow_dispatch: # Allow manual invocation of the workflow

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Set up node
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: install conventional-changelog dependency
      run: npm install -D conventional-changelog
    - name: Bump version and push tag
      uses: eyerate-actions/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.GH_REPO_TOKEN }}
        git-message: "chore(release): {version}"
        release-count: 0
        skip-on-empty: false
        config-file-path: ".versionrc.js"
